FROM alpine

ADD ./bin/liberatorBlockedWorker /app/bin/liberatorBlockedWorker
COPY ./dist ./app/bin/web
RUN chmod +x /app/bin/liberatorBlockedWorker
WORKDIR /app
RUN apk --no-cache add ca-certificates
CMD ["/app/bin/liberatorBlockedWorker", "-d", "false"]