FROM alpine

ADD ./bin/rawImageHandler /app/bin/rawImageHandler
COPY ./dist ./app/bin/web
RUN chmod +x /app/bin/rawImageHandler
WORKDIR /app
RUN apk --no-cache add ca-certificates
CMD ["/app/bin/rawImageHandler", "-d", "false"]